#include <xylose/random/Crappy.hpp>

#include <fstream>
#include <vector>
#include <iostream>


int main () {
  std::cout << 
    "This program is for generating binary output files from the old Crappy random\n"
    "number generator.  There are two files generated which can be used as\n"
    "input to a random number testing package (such as DIEHARD by George\n"
    "Marsaglia).  The two files generated are:\n"
    "       test_crappy.dat\n"
    "           A sequence of random numbers generated by a single Crappy\n"
    "           instance that has been seeded with the default seed values\n"
    "           (Default seeds are 1,2,3,4).\n"
    "       test_crappy-intlv.dat\n"
    "           A sequence of random numbers generated by a set of Crappy\n"
    "           instances.  For each iteration, all the generators are\n"
    "           sequentially queried such that each number in the file\n"
    "           is from the same RNG generation as the numbers around it.\n"
            << std::endl;


  using xylose::random::Crappy;
  typedef xylose::make_vector<uint32_t,5u> mkV5;

  const int total_rolls = 6000000;

#ifdef BOOST_TEST
  {
    typedef Crappy::SeedVector V5T;
    Crappy r(
      mkV5()( 2981107794, 1283166457, 3823313073, 2005073031, 2954216106 )
    );

    BOOST_CHECK_EQUAL( static_cast<int32_t>(r.randInt()) >= 0 );
  }
#endif

  {
    Crappy r;

    std::ofstream out("test_crappy.dat");
    for ( int i = 0; i < total_rolls; ++i) {
      uint32_t val = r.randInt();
      out.write((char*)&val, sizeof(uint32_t));
    }
    out.close();
  }

  {
    static const uint64_t mx = total_rolls; //static_cast<uint32_t>(-1);
    for ( uint64_t i = 0; i <= mx; ++i) {
      double n = Crappy( static_cast<uint32_t>(i) ).randExc();
      if ( n >= 1 || n < 0 )
        std::cout << __FILE__ "got a bad rand nubmer (" <<n
                  <<") for seed ("<<i<<')' << std::endl;
    }
  }


  {
    const int n_generators = 100000;
    const int max_iter = total_rolls / n_generators;

    Crappy sr;
    std::vector<Crappy> rv;
    for (int i = 0; i < n_generators; ++i) {
      typedef Crappy::SeedVector V5T;
      rv.push_back(
        Crappy(
          mkV5()( sr.randInt(),
                  sr.randInt(),
                  sr.randInt(),
                  sr.randInt(),
                  sr.randInt() )
        )
      );
    }

    std::ofstream out("test_crappy-intlv.dat");
    for ( int i = 0; i < max_iter; ++i) {
      for (int n = 0; n < n_generators; ++n) {
        uint32_t val = rv[n].randInt();
        out.write((char*)&val, sizeof(uint32_t));
      }
    }
    out.close();
  }

  return 0;
}

