/*==============================================================================
 * Public Domain Contributions 2010 United States Government                   *
 * as represented by the U.S. Air Force Research Laboratory.                   *
 *                                                                             *
 * This file is part of xylose                                                 *
 *                                                                             *
 * This program is free software: you can redistribute it and/or modify it     *
 * under the terms of the GNU Lesser General Public License as published by    *
 * the Free Software Foundation, either version 3 of the License, or (at your  *
 * option) any later version.                                                  *
 *                                                                             *
 * This program is distributed in the hope that it will be useful, but WITHOUT *
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or       *
 * FITNESS FOR A PARTICULAR PURPOSE.  See the GNU Lesser General Public        *
 * License for more details.                                                   *
 *                                                                             *
 * You should have received a copy of the GNU Lesser General Public License    *
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.       *
 *                                                                             *
 -----------------------------------------------------------------------------*/

#define BOOST_TEST_MODULE random_Crappy

#include <xylose/random/Crappy.hpp>
#include <xylose/Timer.h>

#include <boost/test/unit_test.hpp>
#include <boost/cstdint.hpp>

#include <fstream>
#include <vector>
#include <iostream>

namespace {
  using  boost::int32_t;
  using boost::uint32_t;
}

BOOST_AUTO_TEST_CASE( generation ) {
  BOOST_TEST_MESSAGE(
    "This program is for generating binary output files from the old Crappy random\n"
    "number generator.  There are two files generated which can be used as\n"
    "input to a random number testing package (such as DIEHARD by George\n"
    "Marsaglia).  The two files generated are:\n"
    "       test_crappy.dat\n"
    "           A sequence of random numbers generated by a single Crappy\n"
    "           instance that has been seeded with the default seed values\n"
    "           (Default seeds are 1,2,3,4).\n"
    "       test_crappy-intlv.dat\n"
    "           A sequence of random numbers generated by a set of Crappy\n"
    "           instances.  For each iteration, all the generators are\n"
    "           sequentially queried such that each number in the file\n"
    "           is from the same RNG generation as the numbers around it.\n"
  );


  using xylose::random::Crappy;
  typedef xylose::make_vector<uint32_t,5u> mkV5;

  const int total_rolls = 6000000;

#ifdef BOOST_TEST
  {
    typedef Crappy::SeedVector V5T;
    Crappy r(
      mkV5()( 2981107794, 1283166457, 3823313073, 2005073031, 2954216106 )
    );

    BOOST_CHECK_EQUAL( static_cast<int32_t>(r.randInt()) >= 0 );
  }
#endif

  {
    Crappy r;

    std::ofstream out("test_crappy.dat");
    for ( int i = 0; i < total_rolls; ++i) {
      uint32_t val = r.randInt();
      out.write((char*)&val, sizeof(uint32_t));
    }
    out.close();
  }

  {
    for ( int i = 0; i <= total_rolls; ++i) {
      double n = Crappy( static_cast<uint32_t>(i) ).randExc();
      if ( n >= 1 || n < 0 )
        BOOST_CHECK_MESSAGE( n >= 0 && n < 1,
          __FILE__ "got a bad rand nubmer (" <<n <<") for seed ("<<i<<')'
        );
    }
  }

  {
    Crappy r;
    std::ofstream out("test_crappy_randExc.dat");
    for ( int i = 0; i < total_rolls; ++i)
      out << r.randExc() << '\n';
    out.close();
  }


  {
    const int n_generators = 100000;
    const int max_iter = total_rolls / n_generators;

    Crappy sr;
    std::vector<Crappy> rv;
    for (int i = 0; i < n_generators; ++i) {
      typedef Crappy::SeedVector V5T;
      rv.push_back(
        Crappy(
          mkV5()( sr.randInt(),
                  sr.randInt(),
                  sr.randInt(),
                  sr.randInt(),
                  sr.randInt() )
        )
      );
    }

    std::ofstream out("test_crappy-intlv.dat");
    for ( int i = 0; i < max_iter; ++i) {
      for (int n = 0; n < n_generators; ++n) {
        uint32_t val = rv[n].randInt();
        out.write((char*)&val, sizeof(uint32_t));
      }
    }
    out.close();
  }

  {
    Crappy r;
    unsigned long junk = 0u;
    xylose::Timer timer;
    timer.start();
    for ( unsigned long i = 0; i < 100000000UL; ++i ) {
      junk ^= r.randInt();
    }
    timer.stop();

    /* make sure that junk isn't optimized away */
    BOOST_CHECK_EQUAL( junk, junk );

    BOOST_TEST_MESSAGE(
      "Generation rate:  "
      << (1e2 / timer.dt) << " million per second \n"
         "                  "
      << (1e2 / timer.dt_cpu_time) << " million per cpu second"
    );
  }

}

